<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create(["name"=>"PIDIE JAYA", "province_id"=>1]);
        City::create(["name"=>"SIMEULUE", "province_id"=>1]);
        City::create(["name"=>"BIREUEN", "province_id"=>1]);
        City::create(["name"=>"ACEH TIMUR", "province_id"=>1]);
        City::create(["name"=>"ACEH UTARA", "province_id"=>1]);
        City::create(["name"=>"PIDIE", "province_id"=>1]);
        City::create(["name"=>"ACEH BARAT DAYA", "province_id"=>1]);
        City::create(["name"=>"GAYO LUES", "province_id"=>1]);
        City::create(["name"=>"ACEH SELATAN", "province_id"=>1]);
        City::create(["name"=>"ACEH TAMIANG", "province_id"=>1]);
        City::create(["name"=>"ACEH BESAR", "province_id"=>1]);
        City::create(["name"=>"ACEH TENGGARA", "province_id"=>1]);
        City::create(["name"=>"BENER MERIAH", "province_id"=>1]);
        City::create(["name"=>"ACEH JAYA", "province_id"=>1]);
        City::create(["name"=>"LHOKSEUMAWE", "province_id"=>1]);
        City::create(["name"=>"ACEH BARAT", "province_id"=>1]);
        City::create(["name"=>"NAGAN RAYA", "province_id"=>1]);
        City::create(["name"=>"LANGSA", "province_id"=>1]);
        City::create(["name"=>"BANDA ACEH", "province_id"=>1]);
        City::create(["name"=>"ACEH SINGKIL", "province_id"=>1]);
        City::create(["name"=>"SABANG", "province_id"=>1]);
        City::create(["name"=>"ACEH TENGAH", "province_id"=>1]);
        City::create(["name"=>"SUBULUSSALAM", "province_id"=>1]);
        City::create(["name"=>"NIAS SELATAN", "province_id"=>2]);
        City::create(["name"=>"MANDAILING NATAL", "province_id"=>2]);
        City::create(["name"=>"DAIRI", "province_id"=>2]);
        City::create(["name"=>"LABUHAN BATU UTARA", "province_id"=>2]);
        City::create(["name"=>"TAPANULI UTARA", "province_id"=>2]);
        City::create(["name"=>"SIMALUNGUN", "province_id"=>2]);
        City::create(["name"=>"LANGKAT", "province_id"=>2]);
        City::create(["name"=>"SERDANG BEDAGAI", "province_id"=>2]);
        City::create(["name"=>"TAPANULI SELATAN", "province_id"=>2]);
        City::create(["name"=>"ASAHAN", "province_id"=>2]);
        City::create(["name"=>"PADANG LAWAS UTARA", "province_id"=>2]);
        City::create(["name"=>"PADANG LAWAS", "province_id"=>2]);
        City::create(["name"=>"LABUHAN BATU SELATAN", "province_id"=>2]);
        City::create(["name"=>"PADANG SIDEMPUAN", "province_id"=>2]);
        City::create(["name"=>"TOBA SAMOSIR", "province_id"=>2]);
        City::create(["name"=>"TAPANULI TENGAH", "province_id"=>2]);
        City::create(["name"=>"HUMBANG HASUNDUTAN", "province_id"=>2]);
        City::create(["name"=>"SIBOLGA", "province_id"=>2]);
        City::create(["name"=>"BATU BARA", "province_id"=>2]);
        City::create(["name"=>"SAMOSIR", "province_id"=>2]);
        City::create(["name"=>"PEMATANG SIANTAR", "province_id"=>2]);
        City::create(["name"=>"LABUHAN BATU", "province_id"=>2]);
        City::create(["name"=>"DELI SERDANG", "province_id"=>2]);
        City::create(["name"=>"GUNUNGSITOLI", "province_id"=>2]);
        City::create(["name"=>"NIAS UTARA", "province_id"=>2]);
        City::create(["name"=>"NIAS", "province_id"=>2]);
        City::create(["name"=>"KARO", "province_id"=>2]);
        City::create(["name"=>"NIAS BARAT", "province_id"=>2]);
        City::create(["name"=>"MEDAN", "province_id"=>2]);
        City::create(["name"=>"PAKPAK BHARAT", "province_id"=>2]);
        City::create(["name"=>"TEBING TINGGI", "province_id"=>2]);
        City::create(["name"=>"BINJAI", "province_id"=>2]);
        City::create(["name"=>"TANJUNG BALAI", "province_id"=>2]);
        City::create(["name"=>"DHARMASRAYA", "province_id"=>3]);
        City::create(["name"=>"SOLOK SELATAN", "province_id"=>3]);
        City::create(["name"=>"SIJUNJUNG (SAWAH LUNTO SIJUNJUNG)", "province_id"=>3]);
        City::create(["name"=>"PASAMAN BARAT", "province_id"=>3]);
        City::create(["name"=>"SOLOK", "province_id"=>3]);
        City::create(["name"=>"PASAMAN", "province_id"=>3]);
        City::create(["name"=>"PARIAMAN", "province_id"=>3]);
        City::create(["name"=>"TANAH DATAR", "province_id"=>3]);
        City::create(["name"=>"PADANG PARIAMAN", "province_id"=>3]);
        City::create(["name"=>"PESISIR SELATAN", "province_id"=>3]);
        City::create(["name"=>"PADANG", "province_id"=>3]);
        City::create(["name"=>"SAWAH LUNTO", "province_id"=>3]);
        City::create(["name"=>"LIMA PULUH KOTO / KOTA", "province_id"=>3]);
        City::create(["name"=>"AGAM", "province_id"=>3]);
        City::create(["name"=>"PAYAKUMBUH", "province_id"=>3]);
        City::create(["name"=>"BUKITTINGGI", "province_id"=>3]);
        City::create(["name"=>"PADANG PANJANG", "province_id"=>3]);
        City::create(["name"=>"KEPULAUAN MENTAWAI", "province_id"=>3]);
        City::create(["name"=>"INDRAGIRI HILIR", "province_id"=>4]);
        City::create(["name"=>"KUANTAN SINGINGI", "province_id"=>4]);
        City::create(["name"=>"PELALAWAN", "province_id"=>4]);
        City::create(["name"=>"PEKANBARU", "province_id"=>4]);
        City::create(["name"=>"ROKAN HILIR", "province_id"=>4]);
        City::create(["name"=>"BENGKALIS", "province_id"=>4]);
        City::create(["name"=>"INDRAGIRI HULU", "province_id"=>4]);
        City::create(["name"=>"ROKAN HULU", "province_id"=>4]);
        City::create(["name"=>"KAMPAR", "province_id"=>4]);
        City::create(["name"=>"KEPULAUAN MERANTI", "province_id"=>4]);
        City::create(["name"=>"DUMAI", "province_id"=>4]);
        City::create(["name"=>"SIAK", "province_id"=>4]);
        City::create(["name"=>"TEBO", "province_id"=>5]);
        City::create(["name"=>"TANJUNG JABUNG BARAT", "province_id"=>5]);
        City::create(["name"=>"MUARO JAMBI", "province_id"=>5]);
        City::create(["name"=>"KERINCI", "province_id"=>5]);
        City::create(["name"=>"MERANGIN", "province_id"=>5]);
        City::create(["name"=>"BUNGO", "province_id"=>5]);
        City::create(["name"=>"TANJUNG JABUNG TIMUR", "province_id"=>5]);
        City::create(["name"=>"SUNGAIPENUH", "province_id"=>5]);
        City::create(["name"=>"BATANG HARI", "province_id"=>5]);
        City::create(["name"=>"JAMBI", "province_id"=>5]);
        City::create(["name"=>"SAROLANGUN", "province_id"=>5]);
        City::create(["name"=>"PALEMBANG", "province_id"=>6]);
        City::create(["name"=>"LAHAT", "province_id"=>6]);
        City::create(["name"=>"OGAN KOMERING ULU TIMUR", "province_id"=>6]);
        City::create(["name"=>"MUSI BANYUASIN", "province_id"=>6]);
        City::create(["name"=>"PAGAR ALAM", "province_id"=>6]);
        City::create(["name"=>"OGAN KOMERING ULU SELATAN", "province_id"=>6]);
        City::create(["name"=>"BANYUASIN", "province_id"=>6]);
        City::create(["name"=>"MUSI RAWAS", "province_id"=>6]);
        City::create(["name"=>"MUARA ENIM", "province_id"=>6]);
        City::create(["name"=>"OGAN KOMERING ULU", "province_id"=>6]);
        City::create(["name"=>"OGAN KOMERING ILIR", "province_id"=>6]);
        City::create(["name"=>"EMPAT LAWANG", "province_id"=>6]);
        City::create(["name"=>"LUBUK LINGGAU", "province_id"=>6]);
        City::create(["name"=>"PRABUMULIH", "province_id"=>6]);
        City::create(["name"=>"OGAN ILIR", "province_id"=>6]);
        City::create(["name"=>"BENGKULU TENGAH", "province_id"=>7]);
        City::create(["name"=>"REJANG LEBONG", "province_id"=>7]);
        City::create(["name"=>"MUKO MUKO", "province_id"=>7]);
        City::create(["name"=>"KAUR", "province_id"=>7]);
        City::create(["name"=>"BENGKULU UTARA", "province_id"=>7]);
        City::create(["name"=>"LEBONG", "province_id"=>7]);
        City::create(["name"=>"KEPAHIANG", "province_id"=>7]);
        City::create(["name"=>"BENGKULU SELATAN", "province_id"=>7]);
        City::create(["name"=>"SELUMA", "province_id"=>7]);
        City::create(["name"=>"BENGKULU", "province_id"=>7]);
        City::create(["name"=>"LAMPUNG UTARA", "province_id"=>8]);
        City::create(["name"=>"WAY KANAN", "province_id"=>8]);
        City::create(["name"=>"LAMPUNG TENGAH", "province_id"=>8]);
        City::create(["name"=>"MESUJI", "province_id"=>8]);
        City::create(["name"=>"PRINGSEWU", "province_id"=>8]);
        City::create(["name"=>"LAMPUNG TIMUR", "province_id"=>8]);
        City::create(["name"=>"LAMPUNG SELATAN", "province_id"=>8]);
        City::create(["name"=>"TULANG BAWANG", "province_id"=>8]);
        City::create(["name"=>"TULANG BAWANG BARAT", "province_id"=>8]);
        City::create(["name"=>"TANGGAMUS", "province_id"=>8]);
        City::create(["name"=>"LAMPUNG BARAT", "province_id"=>8]);
        City::create(["name"=>"PESISIR BARAT", "province_id"=>8]);
        City::create(["name"=>"PESAWARAN", "province_id"=>8]);
        City::create(["name"=>"BANDAR LAMPUNG", "province_id"=>8]);
        City::create(["name"=>"METRO", "province_id"=>8]);
        City::create(["name"=>"BELITUNG", "province_id"=>9]);
        City::create(["name"=>"BELITUNG TIMUR", "province_id"=>9]);
        City::create(["name"=>"BANGKA", "province_id"=>9]);
        City::create(["name"=>"BANGKA SELATAN", "province_id"=>9]);
        City::create(["name"=>"BANGKA BARAT", "province_id"=>9]);
        City::create(["name"=>"PANGKAL PINANG", "province_id"=>9]);
        City::create(["name"=>"BANGKA TENGAH", "province_id"=>9]);
        City::create(["name"=>"KEPULAUAN ANAMBAS", "province_id"=>10]);
        City::create(["name"=>"BINTAN", "province_id"=>10]);
        City::create(["name"=>"NATUNA", "province_id"=>10]);
        City::create(["name"=>"BATAM", "province_id"=>10]);
        City::create(["name"=>"TANJUNG PINANG", "province_id"=>10]);
        City::create(["name"=>"KARIMUN", "province_id"=>10]);
        City::create(["name"=>"LINGGA", "province_id"=>10]);
        City::create(["name"=>"JAKARTA UTARA", "province_id"=>11]);
        City::create(["name"=>"JAKARTA BARAT", "province_id"=>11]);
        City::create(["name"=>"JAKARTA TIMUR", "province_id"=>11]);
        City::create(["name"=>"JAKARTA SELATAN", "province_id"=>11]);
        City::create(["name"=>"JAKARTA PUSAT", "province_id"=>11]);
        City::create(["name"=>"KEPULAUAN SERIBU", "province_id"=>11]);
        City::create(["name"=>"DEPOK", "province_id"=>12]);
        City::create(["name"=>"KARAWANG", "province_id"=>12]);
        City::create(["name"=>"CIREBON", "province_id"=>12]);
        City::create(["name"=>"BANDUNG", "province_id"=>12]);
        City::create(["name"=>"SUKABUMI", "province_id"=>12]);
        City::create(["name"=>"SUMEDANG", "province_id"=>12]);
        City::create(["name"=>"INDRAMAYU", "province_id"=>12]);
        City::create(["name"=>"MAJALENGKA", "province_id"=>12]);
        City::create(["name"=>"KUNINGAN", "province_id"=>12]);
        City::create(["name"=>"TASIKMALAYA", "province_id"=>12]);
        City::create(["name"=>"CIAMIS", "province_id"=>12]);
        City::create(["name"=>"SUBANG", "province_id"=>12]);
        City::create(["name"=>"PURWAKARTA", "province_id"=>12]);
        City::create(["name"=>"BOGOR", "province_id"=>12]);
        City::create(["name"=>"BEKASI", "province_id"=>12]);
        City::create(["name"=>"GARUT", "province_id"=>12]);
        City::create(["name"=>"PANGANDARAN", "province_id"=>12]);
        City::create(["name"=>"CIANJUR", "province_id"=>12]);
        City::create(["name"=>"BANJAR", "province_id"=>12]);
        City::create(["name"=>"BANDUNG BARAT", "province_id"=>12]);
        City::create(["name"=>"CIMAHI", "province_id"=>12]);
        City::create(["name"=>"PURBALINGGA", "province_id"=>13]);
        City::create(["name"=>"KEBUMEN", "province_id"=>13]);
        City::create(["name"=>"MAGELANG", "province_id"=>13]);
        City::create(["name"=>"CILACAP", "province_id"=>13]);
        City::create(["name"=>"BATANG", "province_id"=>13]);
        City::create(["name"=>"BANJARNEGARA", "province_id"=>13]);
        City::create(["name"=>"BLORA", "province_id"=>13]);
        City::create(["name"=>"BREBES", "province_id"=>13]);
        City::create(["name"=>"BANYUMAS", "province_id"=>13]);
        City::create(["name"=>"WONOSOBO", "province_id"=>13]);
        City::create(["name"=>"TEGAL", "province_id"=>13]);
        City::create(["name"=>"PURWOREJO", "province_id"=>13]);
        City::create(["name"=>"PATI", "province_id"=>13]);
        City::create(["name"=>"SUKOHARJO", "province_id"=>13]);
        City::create(["name"=>"KARANGANYAR", "province_id"=>13]);
        City::create(["name"=>"PEKALONGAN", "province_id"=>13]);
        City::create(["name"=>"PEMALANG", "province_id"=>13]);
        City::create(["name"=>"BOYOLALI", "province_id"=>13]);
        City::create(["name"=>"GROBOGAN", "province_id"=>13]);
        City::create(["name"=>"SEMARANG", "province_id"=>13]);
        City::create(["name"=>"DEMAK", "province_id"=>13]);
        City::create(["name"=>"REMBANG", "province_id"=>13]);
        City::create(["name"=>"KLATEN", "province_id"=>13]);
        City::create(["name"=>"KUDUS", "province_id"=>13]);
        City::create(["name"=>"TEMANGGUNG", "province_id"=>13]);
        City::create(["name"=>"SRAGEN", "province_id"=>13]);
        City::create(["name"=>"JEPARA", "province_id"=>13]);
        City::create(["name"=>"WONOGIRI", "province_id"=>13]);
        City::create(["name"=>"KENDAL", "province_id"=>13]);
        City::create(["name"=>"SURAKARTA (SOLO)", "province_id"=>13]);
        City::create(["name"=>"SALATIGA", "province_id"=>13]);
        City::create(["name"=>"SLEMAN", "province_id"=>14]);
        City::create(["name"=>"BANTUL", "province_id"=>14]);
        City::create(["name"=>"YOGYAKARTA", "province_id"=>14]);
        City::create(["name"=>"GUNUNG KIDUL", "province_id"=>14]);
        City::create(["name"=>"KULON PROGO", "province_id"=>14]);
        City::create(["name"=>"GRESIK", "province_id"=>15]);
        City::create(["name"=>"KEDIRI", "province_id"=>15]);
        City::create(["name"=>"SAMPANG", "province_id"=>15]);
        City::create(["name"=>"BANGKALAN", "province_id"=>15]);
        City::create(["name"=>"SUMENEP", "province_id"=>15]);
        City::create(["name"=>"SITUBONDO", "province_id"=>15]);
        City::create(["name"=>"SURABAYA", "province_id"=>15]);
        City::create(["name"=>"JEMBER", "province_id"=>15]);
        City::create(["name"=>"PAMEKASAN", "province_id"=>15]);
        City::create(["name"=>"JOMBANG", "province_id"=>15]);
        City::create(["name"=>"PROBOLINGGO", "province_id"=>15]);
        City::create(["name"=>"BANYUWANGI", "province_id"=>15]);
        City::create(["name"=>"PASURUAN", "province_id"=>15]);
        City::create(["name"=>"BOJONEGORO", "province_id"=>15]);
        City::create(["name"=>"BONDOWOSO", "province_id"=>15]);
        City::create(["name"=>"MAGETAN", "province_id"=>15]);
        City::create(["name"=>"LUMAJANG", "province_id"=>15]);
        City::create(["name"=>"MALANG", "province_id"=>15]);
        City::create(["name"=>"BLITAR", "province_id"=>15]);
        City::create(["name"=>"SIDOARJO", "province_id"=>15]);
        City::create(["name"=>"LAMONGAN", "province_id"=>15]);
        City::create(["name"=>"PACITAN", "province_id"=>15]);
        City::create(["name"=>"TULUNGAGUNG", "province_id"=>15]);
        City::create(["name"=>"MOJOKERTO", "province_id"=>15]);
        City::create(["name"=>"MADIUN", "province_id"=>15]);
        City::create(["name"=>"PONOROGO", "province_id"=>15]);
        City::create(["name"=>"NGAWI", "province_id"=>15]);
        City::create(["name"=>"NGANJUK", "province_id"=>15]);
        City::create(["name"=>"TUBAN", "province_id"=>15]);
        City::create(["name"=>"TRENGGALEK", "province_id"=>15]);
        City::create(["name"=>"BATU", "province_id"=>15]);
        City::create(["name"=>"TANGERANG", "province_id"=>16]);
        City::create(["name"=>"SERANG", "province_id"=>16]);
        City::create(["name"=>"PANDEGLANG", "province_id"=>16]);
        City::create(["name"=>"LEBAK", "province_id"=>16]);
        City::create(["name"=>"TANGERANG SELATAN", "province_id"=>16]);
        City::create(["name"=>"CILEGON", "province_id"=>16]);
        City::create(["name"=>"KLUNGKUNG", "province_id"=>17]);
        City::create(["name"=>"KARANGASEM", "province_id"=>17]);
        City::create(["name"=>"BANGLI", "province_id"=>17]);
        City::create(["name"=>"TABANAN", "province_id"=>17]);
        City::create(["name"=>"GIANYAR", "province_id"=>17]);
        City::create(["name"=>"BADUNG", "province_id"=>17]);
        City::create(["name"=>"JEMBRANA", "province_id"=>17]);
        City::create(["name"=>"BULELENG", "province_id"=>17]);
        City::create(["name"=>"DENPASAR", "province_id"=>17]);
        City::create(["name"=>"MATARAM", "province_id"=>18]);
        City::create(["name"=>"DOMPU", "province_id"=>18]);
        City::create(["name"=>"SUMBAWA BARAT", "province_id"=>18]);
        City::create(["name"=>"SUMBAWA", "province_id"=>18]);
        City::create(["name"=>"LOMBOK TENGAH", "province_id"=>18]);
        City::create(["name"=>"LOMBOK TIMUR", "province_id"=>18]);
        City::create(["name"=>"LOMBOK UTARA", "province_id"=>18]);
        City::create(["name"=>"LOMBOK BARAT", "province_id"=>18]);
        City::create(["name"=>"BIMA", "province_id"=>18]);
        City::create(["name"=>"TIMOR TENGAH SELATAN", "province_id"=>19]);
        City::create(["name"=>"FLORES TIMUR", "province_id"=>19]);
        City::create(["name"=>"ALOR", "province_id"=>19]);
        City::create(["name"=>"ENDE", "province_id"=>19]);
        City::create(["name"=>"NAGEKEO", "province_id"=>19]);
        City::create(["name"=>"KUPANG", "province_id"=>19]);
        City::create(["name"=>"SIKKA", "province_id"=>19]);
        City::create(["name"=>"NGADA", "province_id"=>19]);
        City::create(["name"=>"TIMOR TENGAH UTARA", "province_id"=>19]);
        City::create(["name"=>"BELU", "province_id"=>19]);
        City::create(["name"=>"LEMBATA", "province_id"=>19]);
        City::create(["name"=>"SUMBA BARAT DAYA", "province_id"=>19]);
        City::create(["name"=>"SUMBA BARAT", "province_id"=>19]);
        City::create(["name"=>"SUMBA TENGAH", "province_id"=>19]);
        City::create(["name"=>"SUMBA TIMUR", "province_id"=>19]);
        City::create(["name"=>"ROTE NDAO", "province_id"=>19]);
        City::create(["name"=>"MANGGARAI TIMUR", "province_id"=>19]);
        City::create(["name"=>"MANGGARAI", "province_id"=>19]);
        City::create(["name"=>"SABU RAIJUA", "province_id"=>19]);
        City::create(["name"=>"MANGGARAI BARAT", "province_id"=>19]);
        City::create(["name"=>"LANDAK", "province_id"=>20]);
        City::create(["name"=>"KETAPANG", "province_id"=>20]);
        City::create(["name"=>"SINTANG", "province_id"=>20]);
        City::create(["name"=>"KUBU RAYA", "province_id"=>20]);
        City::create(["name"=>"PONTIANAK", "province_id"=>20]);
        City::create(["name"=>"KAYONG UTARA", "province_id"=>20]);
        City::create(["name"=>"BENGKAYANG", "province_id"=>20]);
        City::create(["name"=>"KAPUAS HULU", "province_id"=>20]);
        City::create(["name"=>"SAMBAS", "province_id"=>20]);
        City::create(["name"=>"SINGKAWANG", "province_id"=>20]);
        City::create(["name"=>"SANGGAU", "province_id"=>20]);
        City::create(["name"=>"MELAWI", "province_id"=>20]);
        City::create(["name"=>"SEKADAU", "province_id"=>20]);
        City::create(["name"=>"KOTAWARINGIN TIMUR", "province_id"=>21]);
        City::create(["name"=>"SUKAMARA", "province_id"=>21]);
        City::create(["name"=>"KOTAWARINGIN BARAT", "province_id"=>21]);
        City::create(["name"=>"BARITO TIMUR", "province_id"=>21]);
        City::create(["name"=>"KAPUAS", "province_id"=>21]);
        City::create(["name"=>"PULANG PISAU", "province_id"=>21]);
        City::create(["name"=>"LAMANDAU", "province_id"=>21]);
        City::create(["name"=>"SERUYAN", "province_id"=>21]);
        City::create(["name"=>"KATINGAN", "province_id"=>21]);
        City::create(["name"=>"BARITO SELATAN", "province_id"=>21]);
        City::create(["name"=>"MURUNG RAYA", "province_id"=>21]);
        City::create(["name"=>"BARITO UTARA", "province_id"=>21]);
        City::create(["name"=>"GUNUNG MAS", "province_id"=>21]);
        City::create(["name"=>"PALANGKA RAYA", "province_id"=>21]);
        City::create(["name"=>"TAPIN", "province_id"=>22]);
        City::create(["name"=>"BANJAR", "province_id"=>22]);
        City::create(["name"=>"HULU SUNGAI TENGAH", "province_id"=>22]);
        City::create(["name"=>"TABALONG", "province_id"=>22]);
        City::create(["name"=>"HULU SUNGAI UTARA", "province_id"=>22]);
        City::create(["name"=>"BALANGAN", "province_id"=>22]);
        City::create(["name"=>"TANAH BUMBU", "province_id"=>22]);
        City::create(["name"=>"BANJARMASIN", "province_id"=>22]);
        City::create(["name"=>"KOTABARU", "province_id"=>22]);
        City::create(["name"=>"TANAH LAUT", "province_id"=>22]);
        City::create(["name"=>"HULU SUNGAI SELATAN", "province_id"=>22]);
        City::create(["name"=>"BARITO KUALA", "province_id"=>22]);
        City::create(["name"=>"BANJARBARU", "province_id"=>22]);
        City::create(["name"=>"KUTAI BARAT", "province_id"=>23]);
        City::create(["name"=>"SAMARINDA", "province_id"=>23]);
        City::create(["name"=>"PASER", "province_id"=>23]);
        City::create(["name"=>"KUTAI KARTANEGARA", "province_id"=>23]);
        City::create(["name"=>"BERAU", "province_id"=>23]);
        City::create(["name"=>"PENAJAM PASER UTARA", "province_id"=>23]);
        City::create(["name"=>"BONTANG", "province_id"=>23]);
        City::create(["name"=>"KUTAI TIMUR", "province_id"=>23]);
        City::create(["name"=>"BALIKPAPAN", "province_id"=>23]);
        City::create(["name"=>"MALINAU", "province_id"=>24]);
        City::create(["name"=>"NUNUKAN", "province_id"=>24]);
        City::create(["name"=>"BULUNGAN (BULONGAN)", "province_id"=>24]);
        City::create(["name"=>"TANA TIDUNG", "province_id"=>24]);
        City::create(["name"=>"TARAKAN", "province_id"=>24]);
        City::create(["name"=>"BOLAANG MONGONDOW (BOLMONG)", "province_id"=>25]);
        City::create(["name"=>"BOLAANG MONGONDOW SELATAN", "province_id"=>25]);
        City::create(["name"=>"MINAHASA SELATAN", "province_id"=>25]);
        City::create(["name"=>"BITUNG", "province_id"=>25]);
        City::create(["name"=>"MINAHASA", "province_id"=>25]);
        City::create(["name"=>"KEPULAUAN SANGIHE", "province_id"=>25]);
        City::create(["name"=>"MINAHASA UTARA", "province_id"=>25]);
        City::create(["name"=>"KEPULAUAN TALAUD", "province_id"=>25]);
        City::create(["name"=>"KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)", "province_id"=>25]);
        City::create(["name"=>"MANADO", "province_id"=>25]);
        City::create(["name"=>"BOLAANG MONGONDOW UTARA", "province_id"=>25]);
        City::create(["name"=>"BOLAANG MONGONDOW TIMUR", "province_id"=>25]);
        City::create(["name"=>"MINAHASA TENGGARA", "province_id"=>25]);
        City::create(["name"=>"KOTAMOBAGU", "province_id"=>25]);
        City::create(["name"=>"TOMOHON", "province_id"=>25]);
        City::create(["name"=>"BANGGAI KEPULAUAN", "province_id"=>26]);
        City::create(["name"=>"TOLI-TOLI", "province_id"=>26]);
        City::create(["name"=>"PARIGI MOUTONG", "province_id"=>26]);
        City::create(["name"=>"BUOL", "province_id"=>26]);
        City::create(["name"=>"DONGGALA", "province_id"=>26]);
        City::create(["name"=>"POSO", "province_id"=>26]);
        City::create(["name"=>"MOROWALI", "province_id"=>26]);
        City::create(["name"=>"TOJO UNA-UNA", "province_id"=>26]);
        City::create(["name"=>"BANGGAI", "province_id"=>26]);
        City::create(["name"=>"SIGI", "province_id"=>26]);
        City::create(["name"=>"PALU", "province_id"=>26]);
        City::create(["name"=>"MAROS", "province_id"=>27]);
        City::create(["name"=>"WAJO", "province_id"=>27]);
        City::create(["name"=>"BONE", "province_id"=>27]);
        City::create(["name"=>"SOPPENG", "province_id"=>27]);
        City::create(["name"=>"SIDENRENG RAPPANG / RAPANG", "province_id"=>27]);
        City::create(["name"=>"TAKALAR", "province_id"=>27]);
        City::create(["name"=>"BARRU", "province_id"=>27]);
        City::create(["name"=>"LUWU TIMUR", "province_id"=>27]);
        City::create(["name"=>"SINJAI", "province_id"=>27]);
        City::create(["name"=>"PANGKAJENE KEPULAUAN", "province_id"=>27]);
        City::create(["name"=>"PINRANG", "province_id"=>27]);
        City::create(["name"=>"JENEPONTO", "province_id"=>27]);
        City::create(["name"=>"PALOPO", "province_id"=>27]);
        City::create(["name"=>"TORAJA UTARA", "province_id"=>27]);
        City::create(["name"=>"LUWU", "province_id"=>27]);
        City::create(["name"=>"BULUKUMBA", "province_id"=>27]);
        City::create(["name"=>"MAKASSAR", "province_id"=>27]);
        City::create(["name"=>"SELAYAR (KEPULAUAN SELAYAR)", "province_id"=>27]);
        City::create(["name"=>"TANA TORAJA", "province_id"=>27]);
        City::create(["name"=>"LUWU UTARA", "province_id"=>27]);
        City::create(["name"=>"BANTAENG", "province_id"=>27]);
        City::create(["name"=>"GOWA", "province_id"=>27]);
        City::create(["name"=>"ENREKANG", "province_id"=>27]);
        City::create(["name"=>"PAREPARE", "province_id"=>27]);
        City::create(["name"=>"KOLAKA", "province_id"=>28]);
        City::create(["name"=>"MUNA", "province_id"=>28]);
        City::create(["name"=>"KONAWE SELATAN", "province_id"=>28]);
        City::create(["name"=>"KENDARI", "province_id"=>28]);
        City::create(["name"=>"KONAWE", "province_id"=>28]);
        City::create(["name"=>"KONAWE UTARA", "province_id"=>28]);
        City::create(["name"=>"KOLAKA UTARA", "province_id"=>28]);
        City::create(["name"=>"BUTON", "province_id"=>28]);
        City::create(["name"=>"BOMBANA", "province_id"=>28]);
        City::create(["name"=>"WAKATOBI", "province_id"=>28]);
        City::create(["name"=>"BAU-BAU", "province_id"=>28]);
        City::create(["name"=>"BUTON UTARA", "province_id"=>28]);
        City::create(["name"=>"GORONTALO UTARA", "province_id"=>29]);
        City::create(["name"=>"BONE BOLANGO", "province_id"=>29]);
        City::create(["name"=>"GORONTALO", "province_id"=>29]);
        City::create(["name"=>"BOALEMO", "province_id"=>29]);
        City::create(["name"=>"POHUWATO", "province_id"=>29]);
        City::create(["name"=>"MAJENE", "province_id"=>30]);
        City::create(["name"=>"MAMUJU", "province_id"=>30]);
        City::create(["name"=>"MAMUJU UTARA", "province_id"=>30]);
        City::create(["name"=>"POLEWALI MANDAR", "province_id"=>30]);
        City::create(["name"=>"MAMASA", "province_id"=>30]);
        City::create(["name"=>"MALUKU TENGGARA BARAT", "province_id"=>31]);
        City::create(["name"=>"MALUKU TENGGARA", "province_id"=>31]);
        City::create(["name"=>"SERAM BAGIAN BARAT", "province_id"=>31]);
        City::create(["name"=>"MALUKU TENGAH", "province_id"=>31]);
        City::create(["name"=>"SERAM BAGIAN TIMUR", "province_id"=>31]);
        City::create(["name"=>"MALUKU BARAT DAYA", "province_id"=>31]);
        City::create(["name"=>"AMBON", "province_id"=>31]);
        City::create(["name"=>"BURU", "province_id"=>31]);
        City::create(["name"=>"BURU SELATAN", "province_id"=>31]);
        City::create(["name"=>"KEPULAUAN ARU", "province_id"=>31]);
        City::create(["name"=>"TUAL", "province_id"=>31]);
        City::create(["name"=>"HALMAHERA BARAT", "province_id"=>32]);
        City::create(["name"=>"TIDORE KEPULAUAN", "province_id"=>32]);
        City::create(["name"=>"TERNATE", "province_id"=>32]);
        City::create(["name"=>"PULAU MOROTAI", "province_id"=>32]);
        City::create(["name"=>"KEPULAUAN SULA", "province_id"=>32]);
        City::create(["name"=>"HALMAHERA SELATAN", "province_id"=>32]);
        City::create(["name"=>"HALMAHERA TENGAH", "province_id"=>32]);
        City::create(["name"=>"HALMAHERA TIMUR", "province_id"=>32]);
        City::create(["name"=>"HALMAHERA UTARA", "province_id"=>32]);
        City::create(["name"=>"YALIMO", "province_id"=>33]);
        City::create(["name"=>"DOGIYAI", "province_id"=>33]);
        City::create(["name"=>"ASMAT", "province_id"=>33]);
        City::create(["name"=>"JAYAPURA", "province_id"=>33]);
        City::create(["name"=>"PANIAI", "province_id"=>33]);
        City::create(["name"=>"MAPPI", "province_id"=>33]);
        City::create(["name"=>"TOLIKARA", "province_id"=>33]);
        City::create(["name"=>"PUNCAK JAYA", "province_id"=>33]);
        City::create(["name"=>"PEGUNUNGAN BINTANG", "province_id"=>33]);
        City::create(["name"=>"JAYAWIJAYA", "province_id"=>33]);
        City::create(["name"=>"LANNY JAYA", "province_id"=>33]);
        City::create(["name"=>"NDUGA", "province_id"=>33]);
        City::create(["name"=>"BIAK NUMFOR", "province_id"=>33]);
        City::create(["name"=>"KEPULAUAN YAPEN (YAPEN WAROPEN)", "province_id"=>33]);
        City::create(["name"=>"PUNCAK", "province_id"=>33]);
        City::create(["name"=>"INTAN JAYA", "province_id"=>33]);
        City::create(["name"=>"WAROPEN", "province_id"=>33]);
        City::create(["name"=>"NABIRE", "province_id"=>33]);
        City::create(["name"=>"MIMIKA", "province_id"=>33]);
        City::create(["name"=>"BOVEN DIGOEL", "province_id"=>33]);
        City::create(["name"=>"YAHUKIMO", "province_id"=>33]);
        City::create(["name"=>"SARMI", "province_id"=>33]);
        City::create(["name"=>"MERAUKE", "province_id"=>33]);
        City::create(["name"=>"DEIYAI (DELIYAI)", "province_id"=>33]);
        City::create(["name"=>"KEEROM", "province_id"=>33]);
        City::create(["name"=>"SUPIORI", "province_id"=>33]);
        City::create(["name"=>"MAMBERAMO RAYA", "province_id"=>33]);
        City::create(["name"=>"MAMBERAMO TENGAH", "province_id"=>33]);
        City::create(["name"=>"RAJA AMPAT", "province_id"=>34]);
        City::create(["name"=>"MANOKWARI SELATAN", "province_id"=>34]);
        City::create(["name"=>"MANOKWARI", "province_id"=>34]);
        City::create(["name"=>"KAIMANA", "province_id"=>34]);
        City::create(["name"=>"MAYBRAT", "province_id"=>34]);
        City::create(["name"=>"SORONG SELATAN", "province_id"=>34]);
        City::create(["name"=>"FAKFAK", "province_id"=>34]);
        City::create(["name"=>"PEGUNUNGAN ARFAK", "province_id"=>34]);
        City::create(["name"=>"TAMBRAUW", "province_id"=>34]);
        City::create(["name"=>"SORONG", "province_id"=>34]);
        City::create(["name"=>"TELUK WONDAMA", "province_id"=>34]);
        City::create(["name"=>"TELUK BINTUNI", "province_id"=>34]);

    }
}